### ISSUE TITLE
Restore main repo testing on posthog-production

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog-production#34]
Due to the status of Clickhouse, we had to introduce this temporary change for tests to pass https://github.com/PostHog/posthog-production/pull/27/commits/9d529a07e4215561933a2ecf32d669491eddc800. Once CH is merged, we need to make sure the full test suite is run when making a PR on this repository.

**Comment by paolodamico** [comment]
Also run full test suite here https://github.com/PostHog/posthog/blob/master/.github/workflows/ci-backend.yml on the multi_tenancy tests.

**Comment by Twixes** [comment]
What's the status of this, CH being live now?

**Comment by paolodamico** [comment]
I think you could try re-enabling the entire test suite now

**Comment by paolodamico** [comment]
Addressed on #40.
