### ISSUE TITLE
Infra Diagram not showing

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog-production#71]
@fuziontech the infra diagram on the readme isn't showing.

**Comment by paolodamico** [comment]
Relevant comment https://github.com/PostHog/posthog-production/commit/f345851c0aad458abc22165a8be7483e8b5a060b#r46913779

**Comment by fuziontech** [comment]
Moved it to S3 to fix quickly - #82 moves it to repo like @paolodamico suggests which makes it super straight forward

**Comment by paolodamico** [comment]
Fixed by #82
